.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user-story.md

Add issue templates for bug reports, user stories, and tasks.
Closes #4

Add issue templates for bugs, stories, and tasks

---

.github/workflows/test-suite.yml
app/Http/Controllers/Auth/AuthenticatedSessionController.php
app/Http/Controllers/Auth/ConfirmablePasswordController.php
app/Http/Controllers/Auth/NewPasswordController.php
app/Http/Controllers/Auth/PasswordResetLinkController.php
app/Http/Controllers/Auth/RegisteredUserController.php
composer.json
composer.lock
psalm.xml

Closes #6 
Add Psalm and setup to the repo.
Add Psalm to the CI pipleine with Github actions
*** To run Psalm locally run the following command `./vendor/bin/psalm`

Add and setup psalm and add it to CI pipeline

---

resources/__mocks__/ziggy-js.js
resources/js/Components/Table/CharacterTable/CharacterTable.tsx
resources/js/Layouts/ApplicationLayout/ApplicationLayout.css
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

Closes #97 
-Modify Ziggy's mocked route method
-Add ApplicationLayout CSS
-Add conditional classNames for Inertia Links to set "active" link
-Cherry pick CharacterTable fix from https://github.com/DnD-Montreal/session-tome/commit/15ca7fbac64028c18c2db03b84d82df06d9c2e65
- Login
- Travel between Home and Character page to see Underline move to appropriate link

Implement Menu Highlight

---

database/migrations/2021_11_04_231857_add_cascades_to_entries_table.php
resources/js/Components/Form/CharacterImportForm.test.js
resources/js/Components/Form/CharacterImportForm.tsx

Closes #148 
This pull request will connect the front-end component with back-end, making character import from DNDBeyond or csv file from AL work.

Integrate character import up with backend

---

resources/js/Components/Form/CharacterCreateForm.tsx
resources/js/Layouts/ApplicationLayout/ApplicationLayout.css
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

Closes #166 
Closes #167 
This branch fixes all the noticeable resizing problems and also change the correct prop for edit character switch.

General re-size fix + Edit form privacy setting pre-fill not working

---

cypress/integration/character_exploration.js
cypress/integration/test.js

Closes #168 
Write E2E Cypress tests for Character Exploration #34 user story acceptance criteria.
- Access public character's exploration page
- Access private character's exploration page

test: #168 Add cypress tests to character exploration story

---

.github/workflows/test-suite.yml
sonar-project.properties

Closes #185 
Add sonarcloud to the CI/CD pipeline
Add sonarcloud properties

Add sonarcloud to CI/CD

---

app/Services/AdventuresLeagueAdapter.php

closes #190 
- removes deprecated field manipulation
- refactors entry data by extracting to method call

190 item import fix

---

resources/js/Components/Atom/Link.tsx
resources/js/Components/Form/CharacterCreateForm.tsx
resources/js/Components/Form/CharacterImportForm.tsx
resources/js/Components/Form/DmEntryCreateForm.tsx
resources/js/Components/Table/CharacterTable/CharacterTable.tsx
resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
resources/js/Pages/Character/Character.test.js

Closes #222 
Link button was not clickable outside of the text but within the button

Link button not clickable outside of text

---

resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

Closes #225 
Now the Login text should correctly prompt the popover

Login text to prompt popover

---

resources/js/Components/Atom/StepperForm.tsx
resources/js/Components/Atom/index.ts
resources/js/Components/Form/CharacterCreateForm.tsx
resources/js/Components/index.ts
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

Closes #229 
Adding re-usable stepper form component

Add re-usable stepper form component

---

package.json
resources/js/Components/Table/CharacterTable/CharacterTable.test.js
resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx
resources/js/Components/Table/EntryTable/EntryTable.tsx
yarn.lock

Closes #260 
This branch adds a new package `dayjs`
Dayjs allows us to format dates and compute `DateTime` calculations if needed.

Add day js for formatting

---

app/Http/Controllers/CampaignController.php

Closes #254 
Add filtering to the campaign controller index function to show campaign(s) that the logged-in user is a part of.
1 Assign campaigns to a user
2 In CampaignController dd the following line in the index function `dd($campaigns = Auth::user()->campaigns()->get());`
3 Log into that user
4 Navigate to the campaign route `https://localhost/campaign`
5 Click through the provided collection, in the attributes section you should find the campaigns that were assigned to the user.

Campaign Filtering By Current User

---

resources/js/Components/Table/RatingTable/RatingTable.tsx

Closes #309 
Keeps scroll position when filtering the rating table.

Preserve scroll on rating index table upon filter

---

app/Http/Middleware/Authenticate.php
routes/api.php
tests/Feature/AuthenticationTest.php

Allow Locust access via a bearer token
Implement performance tests
Performance tests will not be stored on this repo. I will provide a GitHub link to the repo once they're complete

Implement Performance Tests

---

app/Http/Controllers/ItemController.php
resources/js/Components/Table/ItemTable/ItemTable.test.js
resources/js/Components/Table/ItemTable/ItemTable.tsx
tests/Feature/Http/Controllers/ItemControllerTest.php

Closes #330 
This branch fixes item deletion not working
On hold: @IanjhPhillips to fix redirecting

Item delete fix

---

resources/js/Components/Form/RatingForm.tsx

Closes #307 
The buttons for ratings when creating an entry for a character overlap and don't look good when the screen is smaller but changes made now make the buttons stack vertically.

Rating buttons in EntryCreateForm overlap on smaller screen

---

app/Http/Controllers/ItemController.php
cypress/integration/Character Management/item_management.js
cypress/support/commands.js
database/seeders/FastSeeder.php
docker-compose.yml
resources/js/Pages/Item/Detail/ItemDetail.tsx
tests/Feature/Http/Controllers/ItemControllerTest.php

Closes #311
Closes #334
Closes #335
- Write E2E Cypress tests for Magic Item Inventory Management #36 user story acceptance criteria.
- Fix redirect after item update.
- Fix item edit form title in drawer
- See list of items
- Edit an item
- Delete an item

Create Cypress Tests for Magic Item Inventory Management

---

cypress/integration/Game Session Tracking/item_entry_management.js

Closes #313
Write E2E Cypress tests for Item Entry Management #107 user story acceptance criteria.
- Create an entry with an item

Cypress Tests for Item Entry Management

---

.github/workflows/test-suite.yml
cypress/integration/Event Management/admin_event_crud.js

Closes #321
Write E2E Cypress tests for Admin Event Control #243 user story acceptance criteria.
- View list of events
- Create an event
- Edit an event
- Delete an event
- View a single event's details

Create Cypress Tests for Admin Event Control

---

app/Http/Controllers/RatingController.php
app/Http/Requests/EntryUpdateRequest.php
cypress/integration/Game Session Tracking/dm-entry-management.js
resources/js/Pages/DMEntry/DMEntry.tsx

Closes #350
Closes #353
Closes #315 
Closes #316
Write E2E Cypress tests for DM Entry Management #111 and #112 user story acceptance criteria.
- View DM Entries
- Create DM Entries
- Assign DM Entries

Create Cypress Tests for DM Entry Management

---

cypress/integration/Player Rating System/rating_lookup.js

Closes #318
Write E2E Cypress tests for Rating Lookup #202 user story acceptance criteria.
- Search for users in the rating table
- Filter ratings specifically from league events

Create Cypress Tests for Rating Lookup

---

cypress/integration/Game Session Tracking/bulk_entry_creation.js

Closes #314
Write E2E Cypress tests for Bulk Entry Creation #108 user story acceptance criteria.
- Create character entries in bulk

Create Cypress Tests for Bulk Entry Creation

---

cypress/integration/Player Rating System/game_master_ratings.js

Closes #317
Write E2E Cypress tests for Game Master Ratings #201 user story acceptance criteria.
- Create entry with ratings
- Check that ratings are added to GM

Create Cypress Tests for Game Master Ratings

---

cypress/integration/Game Session Tracking/entry_management.js

Closes #312
Write E2E Cypress tests for Manage Entries #106 user story acceptance criteria.
- Create a character entry
- Edit a character entry
- Delete a character entry
- List character entries

Create Cypress Tests for Manage Entries

---

.github/workflows/test-suite.yml

Closes #389 
Split cypress pipeline due to long sequential pipeline build time

Split cypress pipeline

---

app/Http/Controllers/CharacterController.php
app/Http/Controllers/EntryController.php
app/Http/Requests/EntryStoreRequest.php
app/Http/Requests/EntryUpdateRequest.php
app/Models/Entry.php
cypress.json
cypress/integration/Game Session Tracking/entry_management.js
cypress/integration/Game Session Tracking/item_entry_management.js
cypress/integration/Player Rating System/game_master_ratings.js
resources/js/Components/Atom/Autocomplete.tsx
resources/js/Components/Atom/Link.tsx
resources/js/Components/Form/BulkEntryCreateForm.test.js
resources/js/Components/Form/BulkEntryCreateForm.tsx
resources/js/Components/Form/DmEntryCreateForm.test.js
resources/js/Components/Form/DmEntryCreateForm.tsx
resources/js/Components/Form/EntryCreateForm.test.js
resources/js/Components/Form/EntryCreateForm.tsx
resources/js/Components/Table/CharacterTable/CharacterTable.tsx
resources/js/Pages/Character/Detail/CharacterDetail.tsx
resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
tests/Feature/Http/Controllers/DMEntryControllerTest.php
tests/Feature/Http/Controllers/EntryControllerTest.php

Closes #295 
Changes game master field to use autocomplete component, however, it should be allowed to input purely string
This affects: 
Character entry creation, edit

Gamemaster field update

---

cypress/integration/Player Rating System/user_rating_reports.js
cypress/plugins/helper-functions.js
cypress/plugins/index.js

Closes #319
Write E2E Cypress tests for #203 User Rating Reports user story acceptance criteria.
- Export a report for all Game Masters as a Site Admin
- Export a report for a league and its Game Masters as a League Admin

User Rating Reports Cypress Tests

---

cypress/integration/Event Management/event_reports.js

Adds back missing cypress test from bad merge + revert in #415

Fix missing Cypress Test

---

app/Http/Controllers/EventController.php
resources/js/Components/Table/EventTable/EventTable.test.js
resources/js/Components/Table/EventTable/EventTable.tsx
resources/js/Components/Table/EventTable/index.ts
resources/js/Components/Table/index.ts
resources/js/Components/index.ts
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
resources/js/Pages/Event/Event.test.js
resources/js/Pages/Event/Event.tsx
resources/js/Pages/Event/index.ts
resources/js/Pages/Welcome.tsx
resources/js/Types/event-data.ts
resources/js/Types/league-data.ts
resources/mock/event-data.ts
tests/Feature/Http/Controllers/EventControllerTest.php

Implementation of the Event index page mockup: 
-Added event index page
-Added event table
-Added necessary data types/mock data

Event index page

---

public/translation_fr.json

Update French translation based on stakeholder's translation sheet.

Update french translations

---

app/Http/Controllers/CharacterController.php
app/Http/Controllers/DMEntryController.php
app/Http/Controllers/EntryController.php
app/Http/Requests/EntryStoreRequest.php
app/Http/Requests/EntryUpdateRequest.php
app/Models/Campaign.php
public/translation_en.json
public/translation_fr.json
resources/js/Components/Form/DmEntryCreateForm.tsx
resources/js/Components/Form/EntryCreateForm.tsx
resources/js/Components/Table/CampaignTable/CampaignTable.tsx
resources/js/Pages/Campaign/Campaign.tsx
resources/js/Pages/Character/Detail/CharacterDetail.tsx
resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
resources/js/Pages/DMEntry/DMEntry.tsx
resources/js/Pages/Entry/Create/DmEntryCreate.tsx
resources/js/Types/entries-data.ts
tests/Feature/Http/Controllers/EntryControllerTest.php

Closes #449 
Added campaign field to entry creates.

Add campaign field to entry creates

---

cypress/integration/Authentication/authentication.js
cypress/support/commands.js
public/translation_en.json
public/translation_fr.json
resources/js/Components/Authentication/Authentication.test.js
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

Closes #303 
Closes #458 
- Change Login and Username font to Roboto on welcome page
- Add missing period at the end of the English translation of the welcome text

Change Username Font

---

resources/js/Components/Form/CharacterCreateForm.tsx
resources/js/Components/Form/DmEntryCreateForm.tsx
resources/js/Components/Form/EntryCreateForm.tsx

Fix a bug where edit drawer does not return to step 1 on submit

Return to step 1 when there is error for edit drawers

---

app/Http/Controllers/CampaignController.php
app/Http/Controllers/CampaignRegistrationController.php
app/Models/Campaign.php
app/Models/User.php
database/migrations/2022_02_27_224955_add_is_owner_to_campaign_user_table.php
tests/Feature/Http/Controllers/CampaignControllerTest.php
tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php

Closes #430 
Adds is_owner column to campaign_user
When creating a campaign, assigns user as owner

Add campaign ownership flag

---

app/Http/Controllers/CharacterController.php
resources/js/Pages/Character/Detail/CharacterDetail.tsx

Closes #428 
Character detail entry edit to use the correct form in drawer

Character detail to use correct edit entry form

---

public/translation_en.json
public/translation_fr.json
resources/js/Components/Table/EventTable/EventTable.tsx
resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx
resources/js/Pages/Event/Event.tsx

Closes #463 
Added translations for event index and future event details page.

Implement Translation for Event Pages

---

package.json
public/translation_en.json
resources/js/Pages/Campaign/Campaign.tsx
resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
resources/js/Pages/Character/Character.tsx
resources/js/Pages/Character/Create/CharacterCreate.tsx
resources/js/Pages/Character/Detail/CharacterDetail.tsx
resources/js/Pages/Character/Detail/Entry/Create/BulkEntryCreate.tsx
resources/js/Pages/Character/Detail/Entry/Create/EntryCreate.tsx
resources/js/Pages/Character/Import/CharacterImport.tsx
resources/js/Pages/DMEntry/DMEntry.tsx
resources/js/Pages/Entry/Create/DmEntryCreate.tsx
resources/js/Pages/Item/Detail/ItemDetail.tsx
resources/js/Pages/Item/Item.tsx
resources/js/Pages/Profile.tsx
resources/js/Pages/Rating/Rating.tsx
resources/js/Pages/Trade/Trade.tsx
resources/js/Pages/Welcome.tsx
resources/js/app.js
yarn.lock

This branch adds default layout and progress bar from inertia.

Add default layout and progress bar

---

app/Http/Requests/TradeRequest.php

#Closes #476
- Fix trade request to authorize admin user

Trade Creation Backpack Bug Fix

---

app/Http/Controllers/CampaignController.php
app/Http/Controllers/CampaignRegistrationController.php
public/translation_en.json
public/translation_fr.json
resources/js/Components/Atom/Select.tsx
resources/js/Components/CampaignJoinModal/CampaignJoinModal.test.js
resources/js/Components/CampaignJoinModal/CampaignJoinModal.tsx
resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
resources/js/Components/Form/CampaignCreateForm.tsx
resources/js/Components/Form/CampaignRegistrationForm/CampaignRegistrationForm.tsx
resources/js/Components/Form/CampaignRegistrationForm/CampaignResgistrationForm.test.js
resources/js/Components/Table/CampaignTable/CampaignTable.tsx
resources/js/Components/Table/EntryTable/EntryTable.tsx
resources/js/Pages/Campaign/Create/CampaignCreate.tsx
resources/js/Pages/Campaign/Detail/CampaignDetail.test.js
resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.test.js
resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.tsx
resources/js/Types/entries-data.ts

closes #418 
- Clicking on the join button in the campaign index will open a modal.
- Input code and clicking join will redirect to join form
- After filling out the fields and clicking join, redirected to campaign index with new campaign added

Connecting Join Form to Backend

---

app/Http/Controllers/CampaignRegistrationController.php
routes/web.php
tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php

Closes #432 
- Add campaign registration destroy route.
- Add campaign registration destroy controller function.
- Add unit tests.

Campaign Kick Endpoint

---

resources/js/Components/Atom/DataTable.tsx
resources/js/Pages/Profile.tsx

This branch fixes 2 small things
- Padding in profile form titles
- Data table empty value not filtering

Data table filter reset

---

app/Http/Controllers/CampaignController.php
app/Http/Requests/CampaignStoreRequest.php
app/Http/Requests/CampaignUpdateRequest.php
app/Models/Campaign.php
tests/Feature/Http/Controllers/CampaignControllerTest.php

Closes #485 
Adjusts validation rules to match expected inputs from front end

Fix validation rules for Campaigns

---

app/Http/Controllers/EventController.php
app/Models/Session.php
resources/js/Pages/Event/Detail/EventDetail.test.js
resources/js/Pages/Event/Detail/EventDetail.tsx
resources/js/Pages/Event/Detail/index.ts
tests/Feature/Http/Controllers/EventControllerTest.php
tests/Unit/Models/SessionTest.php

Closes #482 
- Filter registered sessions

Filter registered sessions on event detail page

---

resources/js/Components/CampaignKickModal/CampaignKickModal.test.js
resources/js/Components/CampaignKickModal/CampaignKickModal.tsx

Added unit test for campaign kick

Add campaign kick unit tests

---

resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.test.js
resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
resources/js/Components/Table/CampaignTable/CampaignTable.test.js
resources/js/Components/Table/CampaignTable/CampaignTable.tsx

Improving tests for CampaignTable and CampaignDetailBox

Improve campaigntable campaigndetailbox tests

---

resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
resources/js/Pages/Campaign/Create/CampaignCreate.tsx
resources/js/Pages/Campaign/Detail/CampaignDetail.tsx
resources/js/Pages/Campaign/Registration/Create/CampaignRegistrationCreate.tsx

Closes #484 
Adapt nullable user character
User will not be able to create entry or see their session played when userCharacter is null

Campaign detail nullable user character

---

resources/js/Components/Detail/EventDetailBox.test.js
resources/js/Components/Modal/EventRegistrationModal.test.js
resources/js/Components/Table/SessionTable/SessionTable.test.js
resources/js/Components/Table/SessionTable/SessionTable.tsx
resources/mock/event-data.ts
resources/mock/session-data.ts

Added tests for:
- EventDetailBox
- EventRegistrationModal
- SessionTable

Added Tests for Event Components

---

resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx

Hide DM entry button when user joined a campaign with a character

---

public/translation_en.json
public/translation_fr.json
resources/js/Components/Form/CampaignForm.tsx
resources/js/Components/Modal/EventRegistrationModal.tsx

Closes #518 
Snackbar added for:
- Campaign create/edit success
- Event register/leave success

Add snackbar new features

---

app/Http/Controllers/CampaignRegistrationController.php
cypress/integration/Campaign Enrollment/campaign_exploration.js
cypress/integration/Campaign Management/campaign_enrollment.js
database/seeders/DatabaseSeeder.php
database/seeders/FastSeeder.php
resources/js/Components/Table/CampaignTable/CampaignTable.tsx

Closes #444 
Closes #538 
- View the list of participating campaigns
- Join a campaign
- Kick a user from a campaign

Cypress Tests for Campaign Enrollment

---

resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx

This branch simply adds webkit scrollbar to the supported browsers, make overflow scroll looks nicer, this selector targets all the MUI components.

Add webkit scrollbar to the app

---

.github/workflows/test-suite.yml

Closes #550 
Remove sonarcloud from CI/CD pipeline

Remove sonarcloud
