.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package.json, resources/js/app.js, yarn.lock
Closes #2 
Adds Husky, commit-lint, eslint, and lint-staged as dependencies, configures git pre-commit hooks to run that validate files are linted and commit messages conform to chosen format / standards.
=> Install Husky Git hooks, Configure commit lint

app/Http/Controllers/DMEntryController.php, app/Http/Controllers/EntryController.php, app/Http/Requests/EntryStoreRequest.php, app/Http/Requests/EntryUpdateRequest.php, app/Observers/EntryObserver.php, routes/web.php, tests/Feature/Http/Controllers/DMEntryControllerTest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #117
- Creates a controller to handle specific behaviour of DM entries which do not belong to a character.
- Upon /entry.store , if type is 'dm' the response will be a redirect to the index of DMEntryController.
- A new view may be needed to be added in the future in case we wish to differentiate listing characterless DM entries from a list of entries on a character.
- Also fixes an issue in web.php routes where some routes did not have middleware.
=> DM Entry Controller

app/Http/Controllers/CharacterBulkAttachDMEntryController.php, app/Http/Requests/AttachDMEntryRequest.php, routes/web.php, tests/Feature/Http/Controllers/DMEntryControllerTest.php
Closes #118
Adds a controller endpoint that accepts an array of entry ids and attaches them to a character belonging to the user.
- Create a character.
- Create a few DM Entries with no `character_id` and note their levels.
- Send a `PUT` request to the `attach-entry-to-character.update` route by passing a character and an array containing the newly created DM Entries.
- Observe the observer adding the levels gained from the DM Entries to the character.
=> 118 Attach DM Entries to a Character

cypress/integration/character_exploration.js, cypress/integration/character_log_migrator.js, cypress/support/index.js, package.json, yarn.lock
Closes #169
Write E2E Cypress tests for Character Exploration #35 user story acceptance criteria.
- Upload a csv from AdventurersLeagueLog
Since the D&D Beyond import feature requires using their platform, making an end-to-end test would be unsafe since the pipeline would depend on their website being up.
=> Add cypress test for character log migrator story

.husky/commit-msg, .husky/pre-commit, app/Actions/CreateEntryItems.php, app/Http/Controllers/EntryController.php, app/Http/Controllers/ItemController.php, app/Http/Requests/EntryStoreRequest.php, app/Http/Requests/EntryUpdateRequest.php, app/Http/Requests/ItemStoreRequest.php, app/Http/Requests/ItemUpdateRequest.php, app/Models/Item.php, composer.json, composer.lock, database/factories/ItemFactory.php, database/migrations/2021_09_23_221026_create_items_table.php, database/migrations/2021_11_22_201558_add_nullables_to_items_table.php, tests/Feature/Http/Controllers/EntryControllerTest.php, tests/Feature/Http/Controllers/ItemControllerTest.php, tests/Unit/Actions/CreateEntryItemsTest.php
Closes #183 
Adds the ability to specify and `items` array in the entry form on `EntryController@create()`. The items array should take a the format specified in #183. Each element in this `items` form array is an array with sub arrays. Each of these sub associative sub arrays specify properties of a particular item (These properties are found on the database, or the `$fillable` array on `Item`).
Installs a Laravel Action package, rather than using "handcrafted" actions, this provides a bit more structure and documentation! see [more information here](https://github.com/lorisleiva/laravel-actions).  
We're still faced with the same issue that doesn't allow for directly testing the endpoint due to sanctum + inertia, but you can test the added action instead, which captures most of the …
=> Add item creation when storing Entries

app/Models/Item.php, app/Services/AdventuresLeagueAdapter.php, database/migrations/2021_09_23_221026_create_items_table.php, database/mocks/dante-bad.csv, database/mocks/dante.csv, tests/Feature/Http/Controllers/AdventuresLeagueImportControllerTest.php
Closes #172 
Fixes bug which caused backend to throw an error for certain exported characters
- added checks for different entry types
- added functionality for importing items as well as entries
pre-existing migration was modified so first:
`php artisan migrate:fresh`
then:
`php artisan tinker`
`$user = User::factory()->create()`
`Auth::login($user)`
`$character = AdventuresLeague::getCharacter(database_path("mocks/dante.csv"))`
observe that donte is imported, a character is created, and entries are attached.
observe the last entry and note down its id, ill refer to it as k, when you run the following command replace k with the id.
`$e = Entry::find(k)`
`$e->items`
observe the two items attached to this entry
=> adventures league import bug fix

app/Http/Controllers/EntryController.php, app/Http/Requests/EntryStoreRequest.php, app/Http/Requests/EntryUpdateRequest.php, tests/Feature/Http/Controllers/DMEntryControllerTest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #184 
Adds EntryController logic to process store and update requests for DM Entries which contain a reward choice. The possible choices include advancement, magic_item and campaign_reward. The store and update requests must modify the items or levels attributes in the entry based on the reward choice.
=> 184 dm entry reward

app/Http/Requests/RatingStoreRequest.php, app/Http/Requests/RatingUpdateRequest.php, app/Models/Rating.php, database/factories/RatingFactory.php, database/migrations/2021_12_27_200344_add_categories_to_ratings_table.php, database/migrations/2021_12_27_211938_drop_score_from_ratings_table.php, tests/Feature/Http/Controllers/RatingControllerTest.php, tests/Unit/Models/RatingTest.php
Closes #205 
Adds the 'categories' field to the Ratings model, which is an integer that tracks which categories of rating a given rating instance has by making use of bit manipulation and bitmasks.
Also adds two query scopes which can be used to filter by rating category, they are
- Rating::withCategories()
- Rating::withoutCategories()
An example of a query using one of the above scopes:
`$friendlyHelpfulRating = Rating::withCategories([
Rating::FRIENDLY_BITMASK,
Rating::HELPFUL_BITMASK,
])->first();`
Also removes the score field from Ratings model, which is no longer needed due to the updated design of the rating system.
open tinker and create a Rating instance, call it `$rating`
Observe the categories field, if it is non zero run the following command, if it is zero it is not a …
=> Rating Categories

app/Actions/CreateEntryItems.php
Closes #209 
Removes item count guard condition in CreateEntryItems action.
This guard condition made it possible to have items not be removed when they should be.
For example a user removes one item and then adds two new ones to a given entry as part of an edit, then with the guard condition the item to be removed would not have been removed.
=> Fix Item Entry Edit Bug

app/Models/User.php, app/Observers/CharacterObserver.php, app/Observers/EntryObserver.php, app/Providers/EventServiceProvider.php, database/migrations/2022_01_12_015440_add_cascades_to_items_table.php, database/migrations/2022_01_12_021419_add_soft_deletes_to_users_table.php, database/seeders/DatabaseSeeder.php, tests/Feature/Http/Controllers/UserControllerTest.php, tests/Unit/Models/UserTest.php, tests/Unit/Observers/CharacterObserver.php, tests/Unit/Observers/CharacterObserverTest.php
Closes #265 
Attempting to delete a character (or a user), raised an integrity constraint violation exception. This was because the character in question still had items, and ratings attached to their entries that were marked for deletion. 
This is solved by adding an observer that instead detaches entries from a character, leaving all the items and entries in tact. 
This approach prevents ratings or traded items from being deleted when a character is removed. 
Additionally soft deletes on users was added. The reasons are 2 fold: 
- Allows for users to be "banned"
- Allows a user to close their account without tossing away ratings and items they've created on the site.
Also adds a "default" account for ease of testing purposes. This account is automatically an admin. The credentials for …
=> Fix Integrity Constraint Error When Deleting Characters

resources/js/Components/Atom/DataTable.tsx
Closes #270 
This branch fixes filter in DataTable
=> Data table search bar not filtering correctly

resources/js/Components/Form/DmEntryCreateForm.tsx
Closes #266 
- GP input field in DMEntryCreateForm now accepts floats
-- Minimum is 0
-- Max 2 decimals
-- Values in TextField rounded up when input exceeds allowed number of decimals
Go to the DM Creation page and input a float format number into the GP text field.
=> GP inputs allow floats

app/Http/Controllers/DMEntryController.php, resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx, resources/js/Components/Table/EntryTable/EntryTable.tsx, resources/js/Utils/formatter.ts, resources/js/Utils/index.ts
closes #273 
- Add missing magic items that were not showing in the 'Magic Items' column in the DM entries table and in the entries table
=> Magic items column missing from DM entries table and entries table

.github/workflows/deploy.yml
Closes #227 
Adds a Github Action which triggers on the publish of a new release. 
When Published, The action simply triggers a deployment on the Production server via a deployment trigger URL.
=> Add Deploy Workflow

app/Http/Controllers/CharacterController.php, app/Http/Controllers/EntryController.php, routes/web.php, tests/Feature/Http/Controllers/CharacterControllerTest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #264  
Expands EntryController's destroy method to delete multiple entries passed as an array of entry IDs. 
Fixes bug in CharacterController's destroy method which allowed bulk character deletion by unauthorized user.
1. Create multiple entries with same user_id
2. Pass all entry ids as an array to destroy method
3. Check if specified entries have been successfully deleted from db
=> Bulk entry delete

app/Http/Controllers/CharacterController.php, app/Models/Entry.php, tests/Unit/Models/EntryTest.php
Closes #296 
Adds proper sorting to lines in entry table. Lines are now sorted by `date_played` in reverse chronological order. Additionally counter for session now counts in the proper direction, labelling the oldest game as "1" and the newest game as "n" where n is the number of games played in 1 adventure.
1. Login to an account with multiple entries for a character (preferably one with the same adventure across at least 2 entries)
2. Navigate to the Character's detail page
3. Observe that the entries are dated from newest to oldest.
4. Observe that the session attribute is also in descending order
=> Sort Entries by Date Played

resources/js/Components/Form/DmEntryCreateForm.tsx, resources/js/Components/Form/EntryCreateForm.tsx, resources/js/Components/Table/DMEntryTable/DMEntryTable.tsx, resources/js/Components/Table/EntryTable/EntryTable.tsx
Closes #286 
- MUI's Date&Time picker used to replace the Date input fields
- Character entries and DM entries now have a date and time precision
- Entry tables now show correct time
1. Create an entry form and assign a date and time
2. Verify date/time selected for said entry
=> Implement DateTime picker for Entry and DMEntry forms

resources/js/Components/Form/EntryCreateForm.tsx
Closes #308 
If GM field is empty
- When clicking continue on the first step of Entry form, skips to 3rd step.
- From the 3rd step, when clicking previous, goes back to first step.
=> Rating step skipped when the gm field is empty

app/Http/Controllers/TradeController.php, tests/Feature/Http/Controllers/TradeControllerTest.php
Closes #377 
Modifies the TradeController's show endpoint to return more data. Also, data returned depends on if the current user is the creator of the given trade or not.
If they are not, they are only shown the character, user, and trade item info. This allows the user to view the character and item that pertain to the trade.
If they are, they are shown the above info as well as offers that have been made against their trade. These offers come in the for of items with their associated character loaded as well, so that the user can audit the character.
=> Trade Detail Response

app/Actions/CreateEntryItems.php, app/Http/Controllers/EntryController.php, app/Http/Requests/EntryStoreRequest.php, app/Http/Requests/EntryUpdateRequest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #381
Changes the Entry update endpoint account for existing items. Achieves this by loading items that already exist and opting to update them rather than deleting all items and then re-creating them.
=> Change Entry Update to no longer delete existing items

resources/js/Components/Atom/Button.tsx, resources/js/Components/Atom/index.ts, resources/js/Components/Authentication/Authentication.tsx, resources/js/Components/Form/CharacterImportForm.tsx, resources/js/Components/Form/DmEntryCreateForm.tsx, resources/js/Components/Form/EntryCreateForm.tsx, resources/js/Components/index.ts, resources/js/Layouts/ApplicationLayout/ApplicationLayout.tsx, resources/js/Pages/Profile.tsx
Closes #407 
Added loading button component which shows circular motion when making requests
This also fixes the user name being too long on resized window
Notable place to test:
character import
=> Loading button

app/Http/Controllers/Admin/SessionCrudController.php, app/Http/Controllers/EventRegistrationController.php, app/Http/Requests/SessionStoreRequest.php, app/Http/Requests/SessionUpdateRequest.php, app/Models/Session.php, database/factories/SessionFactory.php, database/migrations/2022_02_26_215017_add_end_time_to_sessions_table.php, tests/Feature/Http/Controllers/EventRegistrationControllerTest.php, tests/Feature/Http/Controllers/SessionControllerTest.php, tests/Unit/Models/SessionTest.php
Closes #431
When a user attempts to register for an event session, the system will check if that session overlaps with any sessions that the user is registered for as a player or GM.
=> Session Overlap Check

app/Http/Controllers/DMEntryController.php, app/Http/Controllers/EntryController.php, tests/Feature/Http/Controllers/DMEntryControllerTest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #461
Adds a case to entry and DMentry controller create endpoints that allow them to accept campaign_id as part of the request and pass necessary info in the response to allow for the form to be partially autocompleted.
=> Entry create endpoint extension

cypress/integration/Event Management/admin_event_crud.js
Closes #470
Removes last url dependency between tests, so that each test start on the right page.
=> Remove last url dependency between tests

app/Http/Controllers/EventRegistrationController.php, routes/web.php, tests/Feature/Http/Controllers/EventRegistrationControllerTest.php
Closes #438 
Implementation of destroy function in EventRegistrationController to allow user to deregister an owned character from a session. 
- Create a session and a character
- Register character for session using `$character->sessions()->attach($session)` ...(could also make a more formal store request passing the event_id, session_id and character_id instead)
- Make call to destroy function passing it the session object as a parameter and the character's id in the request
- Verify if the session was removed from the character's sessions() collection
=> User deregistration from event session

app/Models/Entry.php, app/Models/Event.php, tests/Unit/Models/EventTest.php
Closes #436 
Adds a query scope that allows events to be filtered by whether a particular user is registered to the event or not. 
Adds an accessor that determines if the logged in user is registered to the event
1. In tinker, check the users registered to a particular event `App\Models\Sessions::where('event_id', "ID HERE")->with('characters')->get()`
2. Choose a `user_id` and try and filter Events by that id, `App\Models\Event::whereRegistered('USER_ID_HERE')->get()`
3. Notice that only the events that the above sessions belonged to were returned
4. Login as that user `Auth::loginUsingId("USER_ID")`
5. Check the accessor works as well `App\Models\Event::find("EVENT_ID)->is_registered`, should return true / false depending if the user is signed up for the event.
=> Add Event filters and accessor to Model

app/Exceptions/ImportException.php, app/Http/Controllers/AdventuresLeagueImportController.php, app/Services/AdventuresLeagueAdapter.php, tests/Feature/Http/Controllers/AdventuresLeagueImportControllerTest.php, tests/Unit/Adapters/AdventuresLeagueTest.php
Closes #424
Previously the adventures league importer and the associated controller were not handling file exceptions correctly.
When the user uploaded a bad file, or a missing file, they were shown a verbose php error. Instead, the controller now redirects them back to the character import page.
Log in as a user
Navigate to the character import page
Attempt to import from a bad file (any file that is not a valid csv is fine, for example an image of your cat)
Check that the user is redirected back to the same page
Attempt to import a valid file (found in the database/mocks directory of the project)
Check the you are redirected to the created character's page
=> Adventures League Import Response Bug Fix

app/Http/Controllers/EventController.php, app/Models/Session.php, database/factories/TradeFactory.php, tests/Feature/Http/Controllers/EventControllerTest.php
Closes #437 
- Filter event index
=> Filter event controller index results

app/Http/Controllers/CampaignRegistrationController.php, database/migrations/2022_03_10_020408_add_unique_constraint_to_campaign_character_table.php
Closes #486 
Prevents a user from registering the same character to the same campaign more than once. 
Additionally prevents a user from being registered to a campaign more than once.
=> Fix campaign character duplication bug

app/Http/Controllers/CampaignRegistrationController.php, tests/Feature/Http/Controllers/CampaignRegistrationControllerTest.php
Closes #492 
Adjusts redirects when joining or creating campaigns to redirect to the appropriate place and return errors where appropriate
=> Fix redirects for campaign registration

resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx, resources/js/Pages/Campaign/Detail/CampaignDetail.tsx, resources/js/Types/campaign-data.ts, resources/mock/campaign-data.ts
=> Hide buttons for campaign non-owners

resources/js/Components/Modal/EventRegistrationModal.test.js, resources/js/Components/Modal/EventRegistrationModal.tsx, resources/js/Components/Table/CampaignTable/CampaignTable.tsx, resources/js/Pages/Event/Detail/EventDetail.tsx
Closes #515 
Changes made:
- Refactor Modal to use atom modal component in EventRegistrationModal
- Test update for EventRegistrationModal
- Remove checkboxes from CampaignTable
=> Refactor modal

app/Exceptions/GMEntryException.php, app/Http/Controllers/DMEntryController.php, app/Http/Controllers/EntryController.php, tests/Feature/Http/Controllers/DMEntryControllerTest.php, tests/Feature/Http/Controllers/EntryControllerTest.php
Closes #519 
Prevents users from creating GM entries for campaigns in which they are not a GM.
Changes the campaigns returned in the GMEntry create endpoint
Also changes the GMEntry auth
=> GM Entry Creation Bug Fix

app/Models/Campaign.php, database/migrations/2022_03_25_001339_add_soft_deletes_to_campaigns_table.php, tests/Feature/Http/Controllers/CampaignControllerTest.php
Closes #512 
Adds soft deletes to campaigns to allow for easily deleting / archiving of campaigns without violating cascade constraints.
This solution avoids messy n+1 detach logic that would have to be added to the destroy logic in the controller. 
Simply attempt to delete a campaign which has entries / ratings attached to it.
=> Fix rating cascade delete error on campaign delete

app/Models/Entry.php
Closes #446 
Minor formatting change, update the computed reward field to return null and instead depend on FE to format / display a specific text.
=> Update Reward accessor to return Null

cypress/integration/Campaign Management/campaign_enrollment_and_entry_creation.js, resources/js/Components/Modal/CampaignKickModal.tsx, resources/js/Components/Table/EntryTable/EntryTable.tsx
Closes #445 
Cypress test for Campaign Entry Creation
Creates entry from character enrolled in campaign and checks from another user's perspective if entry appears in CampaignDetail.
This test was added to the original campaign_enrollment.js test suite to avoid duplicating the joining portion at the start.
=> Cypress test for Campaign Entry Creation

app/Http/Controllers/Admin/SessionCrudController.php, database/factories/CharacterFactory.php, database/factories/EntryFactory.php, database/factories/SessionFactory.php, database/seeders/DatabaseSeeder.php
Adds the missing `seats` column to laravel backpack. This allows Site and league admins to set the available amount of characters that can register for a session. Also adds the missing `language` field
Also adds some more realistic values to factories, so that characters generated now have real races and classes
Hotfix as this is a last minute bug that came up.
Adds These fields:
=> Hotfix: add session seats to backpack

resources/js/Pages/Welcome/Welcome.tsx
Closes #544 
Hide language selector when user is logged in, the property language is bind to user's account
=> Hide language selector when user is logged in

app/Console/Commands/ImportAdventures.php, app/Imports/AdvenutreImport.php, app/Models/Adventure.php, composer.json, composer.lock, database/factories/AdventureFactory.php, database/migrations/2022_06_15_015700_add_tier_to_adventures_table.php, database/mocks/test-adventures.csv, tests/Feature/ImportAdventuresTest.php
Closes #186 
Adds the ability to create many adventures at once by supplying any number of CSVs. Each row in each CSV is hydrated into a record in the `adventures` table. 
CSV files can be sourced from [this google sheet](https://docs.google.com/spreadsheets/d/1omoTExpdh7cdiq9NnfVpf6-CnAkGRbA-FMIiNaZXpvg/edit#gid=828772063).
1. Download the supplied ZIP of files
2. Unzip the files to `storage/app/adventures`
3. Run `php artisan migrate` to get the latest database changes
4. Run `php artisan adventures:import` to start the importer
5. Once complete, observe that the adventures table has new records.
=> Add Adventure importer based of CSV files
